import { beforeAll,describe,it,expect } from 'vitest';
import RAPIER from '@dimforge/rapier3d-compat';
import * as THREE from 'three';
import { Track } from '../src/track/Track';
import { KartPhysics } from '../src/vehicle/KartPhysics';
import { KARTS } from '../src/config/game';
import { AIDriver } from '../src/ai/AIDriver';
import { RaceManager,advanceProgress } from '../src/race/RaceManager';
import { emptyControls } from '../src/input/InputManager';
import { ItemSystem } from '../src/items/ItemSystem';
beforeAll(async()=>{await RAPIER.init();});
function setup(count=1){const world=new RAPIER.World({x:0,y:-9.81,z:0}),track=new Track(world);world.timestep=1/60;const karts=Array.from({length:count},(_,i)=>new KartPhysics(i,KARTS[i],world,track));const empty=emptyControls();for(let i=0;i<80;i++){for(const k of karts)k.preStep(1/60,empty,false);world.step();for(const k of karts)k.postStep(1/60);}return {world,track,karts};}
describe('Rapier arcade vehicle integration',()=>{
  it('RIGHT input moves SCREEN-RIGHT in a frozen chase camera; LEFT moves SCREEN-LEFT',()=>{for(const sign of [-1,1]){const {world,karts}=setup(),k=karts[0],c=emptyControls();k.spawn(.04,0);c.throttle=1;for(let i=0;i<65;i++){k.preStep(1/60,c);world.step();k.postStep(1/60);}const origin=k.position.clone(),yaw=k.yaw,forward=new THREE.Vector3(Math.sin(yaw),0,Math.cos(yaw));
    // Independent oracle: Three.js's actual view/projection matrix, not the controller's lateral basis.
    const camera=new THREE.PerspectiveCamera(64,16/9,.1,100);camera.position.copy(origin).addScaledVector(forward,-6.1);camera.position.y+=1.65;const look=origin.clone().addScaledVector(forward,7);look.y+=.9;camera.lookAt(look);camera.updateMatrixWorld(true);const before=origin.clone().project(camera);c.steer=sign*.65;for(let i=0;i<30;i++){k.preStep(1/60,c);world.step();k.postStep(1/60);}const after=k.position.clone().project(camera);
    expect((after.x-before.x)*sign).toBeGreaterThan(.015);expect((k.yaw-yaw)*sign).toBeLessThan(-.15);world.free();}});
  it('settles four-ray suspension, drives, jumps, lands and resets',()=>{const {world,karts}=setup(),k=karts[0],c=emptyControls();expect(k.grounded).toBe(true);expect(k.position.y-k.projection.height).toBeGreaterThan(.55);c.throttle=1;for(let i=0;i<60;i++){k.preStep(1/60,c);world.step();k.postStep(1/60);}expect(k.speed).toBeGreaterThan(10);c.jump=true;k.preStep(1/60,c);world.step();k.postStep(1/60);expect(k.body.linvel().y).toBeGreaterThan(3);c.jump=false;c.throttle=0;let air=false,landed=false;for(let i=0;i<150;i++){k.preStep(1/60,c);world.step();k.postStep(1/60);air ||= !k.grounded;landed ||= k.landed>0;}expect(air).toBe(true);expect(landed).toBe(true);k.lastCheckpoint=4;k.reset();expect(k.projection.t).toBeCloseTo(.251,2);expect(k.body.linvel().x).toBe(0);world.free();});
  it('takes off from the real ramp and detects out-of-bounds / inverted chassis',()=>{const {world,track,karts}=setup(),k=karts[0];k.spawn(.11,0);const ai=new AIDriver(k,0);let clearance=0;for(let i=0;i<260;i++){track.update(1/60,i/60);k.preStep(1/60,ai.update(1/60,0));world.step();k.postStep(1/60);if(!k.grounded)clearance=Math.max(clearance,k.position.y-k.projection.height);}expect(clearance).toBeGreaterThan(1.5);k.body.setTranslation({x:200,y:-12,z:200},true);k.postStep(1/60);expect(k.needsReset).toBe(true);k.lastCheckpoint=5;k.reset();expect(k.projection.t).toBeCloseTo(5/16+.001,2);k.body.setRotation({x:1,y:0,z:0,w:0},true);k.postStep(1/60);expect(k.needsReset).toBe(true);world.free();});
  it('shortcut is physically shorter and validates its intermediate gates, never a free gate skip',()=>{const {world,track,karts}=setup(),k=karts[0],{a,b,start,end}=track.shortcut;expect(a.distanceTo(b)).toBeLessThan((end-start)*track.length*.95);k.lastCheckpoint=7;k.nextCheckpoint=8;k.lastT=start;for(let i=1;i<=500;i++){const p=a.clone().lerp(b,i/500),projection=track.project(p);advanceProgress(k,projection.t,track.legal(projection,projection.height+.8),.006,i/60);}expect(k.lastCheckpoint).toBe(10);expect(k.lap).toBe(0);const p=track.project(track.point(.4));expect(track.legal(p,p.height-3)).toBe(false);world.free();});
  it('charges independent drift grip and grants release boost',()=>{const {world,track,karts}=setup(),k=karts[0],c=emptyControls();k.spawn(.34,0);const ai=new AIDriver(k,0);let maxCharge=0,boosted=false;c.throttle=1;for(let i=0;i<330;i++){const a=ai.update(1/60,0);a.drift=i>50&&i<260;k.preStep(1/60,a);world.step();k.postStep(1/60);maxCharge=Math.max(maxCharge,k.driftCharge);boosted ||= k.releasedBoost>0;track.update(1/60,i/60);}expect(maxCharge).toBeGreaterThan(.55);expect(boosted).toBe(true);world.free();});
  it('four colliding AI-controlled karts complete the legal 3-lap race',()=>{const {world,track,karts}=setup(4),race=new RaceManager(karts,'quick'),items=new ItemSystem(track,karts,'quick'),ais=karts.map((k,i)=>new AIDriver(k,[-1,-2.7,2.8,.2][i]));race.start();const empty=emptyControls();let resets=0;
    for(let i=0;i<24000;i++){const active=race.state==='racing'||race.state==='finished';track.update(1/60,i/60);for(let j=0;j<karts.length;j++){const k=karts[j],c=ais[j].update(1/60,karts[0].progress,items);if(k.needsReset){k.reset();resets++;}if(active){if(c.item1)items.use(k,0,c.backward);if(c.item2)items.use(k,1,c.backward);}k.preStep(1/60,k.finished?empty:c,active&&!k.finished);}items.update(1/60,i/60,active);world.step();for(const k of karts)k.postStep(1/60);race.step(1/60);if(karts.every(k=>k.finished))break;}
    console.log('AI finish',karts.map(k=>({id:k.id,lap:k.lap,cp:k.lastCheckpoint,t:k.projection.t,speed:k.speed,time:k.finishTime,off:k.projection.distance,y:k.position.y,height:k.projection.height,shortcut:k.projection.shortcut})),{resets});expect(karts.every(k=>k.finished)).toBe(true);expect(karts.every(k=>k.lapTimes.length===3)).toBe(true);expect(race.state).toBe('finished');world.free();
  },90000);
  it('gear rebounds exactly once and firefly steers into an offset target',()=>{const {world,track,karts}=setup(2),[owner,target]=karts,items=new ItemSystem(track,karts,'quick');owner.spawn(.04,5);owner.yaw+=Math.PI/2;target.spawn(.08,-3);owner.slots[0]='gear';items.use(owner,0);const gear=items.pool.find(o=>o.active)!;for(let i=0;i<6&&gear.bounces===0;i++)items.update(1/60,i/60,false);expect(gear.bounces).toBe(1);const right=track.at(.04).right;expect(gear.velocity.dot(right)).toBeLessThan(0);gear.position.copy(track.point(.04,-7.2));gear.position.y+=.9;gear.velocity.copy(right).multiplyScalar(-40);for(let i=0;i<5&&gear.active;i++)items.update(1/60,i/60,false);expect(gear.active).toBe(false);
    owner.spawn(.04,0);target.spawn(.085,4.8);target.invulnerable=0;owner.slots[0]='firefly';owner.itemCooldown=0;items.use(owner,0);const firefly=items.pool.find(o=>o.active)!;expect(firefly.target).toBe(target.id);for(let i=0;i<100&&firefly.active;i++)items.update(1/60,i/60,false);expect(target.stun).toBeGreaterThan(0);expect(firefly.active).toBe(false);world.free();});
  it('battery and each attack item have an actual physical effect; pool is reused',()=>{const {world,track,karts}=setup(2),[owner,target]=karts,items=new ItemSystem(track,karts,'quick');owner.slots[0]='battery';expect(items.use(owner,0)).toBe(true);expect(owner.boost).toBe(2.25);expect(items.use(owner,0)).toBe(false);
    for(const kind of ['peel','gear','firefly'] as const){owner.spawn(.05,0);target.spawn(.06,0);owner.slots[0]=kind;owner.itemCooldown=0;target.invulnerable=0;expect(items.use(owner,0)).toBe(true);const o=items.pool.find(o=>o.active)!;target.position.copy(o.position);target.body.setTranslation(target.position,true);items.update(1/60,0,false);expect(target.stun,kind).toBeGreaterThan(0);expect(o.active).toBe(false);}
    expect(items.pool).toHaveLength(36);world.free();});
});
