import { CUPS,ITEMS,KARTS,TRACK_NAME,type Mode,type Quality } from '../config/game';
import { Records,formatTime } from '../storage/Records';
import type { KartPhysics } from '../vehicle/KartPhysics';
import type { RaceManager } from '../race/RaceManager';
import type { Track } from '../track/Track';
export interface UIActions {start:(mode:Mode,kart:number)=>void;resume:()=>void;restart:()=>void;menu:()=>void;quality:(q:Quality)=>void;touch:(on:boolean)=>void;volume:(v:number)=>void}
export class HUD {
  mode:Mode='quick';kart=0;touch=false;private actions?:UIActions;private map:HTMLCanvasElement;private mapCtx:CanvasRenderingContext2D;private mapBackground?:HTMLCanvasElement;
  private lastState='';private toastTimer=0;private selection='home';private lastLap=0;
  constructor(public root:HTMLElement,private records:Records){
    root.innerHTML=`<div id="viewport"></div><div class="speed-vignette" id="speed-fx"></div>
    <div id="loading"><div class="loading-mark">p<span>ϟ</span>k</div><h2>正在给山谷上发条</h2><p id="load-text">初始化 3D 引擎…</p><div class="load-track"><i id="load-bar"></i></div><small>POCKET TURBO KINGDOM</small></div>
    <header id="brand"><a href="#" id="brand-link"><span class="brand-icon">ϟ</span><span>POCKET TURBO<small>K I N G D O M</small></span></a><div class="header-right"><span class="build-tag"><i></i> ORIGINAL 3D RACER · VOL. 01</span><button class="icon-button" id="settings-btn" title="设置" aria-label="设置">⚙</button></div></header>
    <main id="menu" class="menu"><div class="hero-copy"><div class="eyebrow"><span></span> SMALL WHEELS. BIG ADVENTURE.</div><h1>POCKET<br/><span>TURBO</span><em>KINGDOM</em></h1><p class="hero-cn">小小车轮，大大奇遇。</p><p class="hero-description">把风装进口袋，把弯道留给漂移。<br/>你的第一场山谷冒险，现在发车。</p>
    <div class="home-actions" id="home-actions"><button id="play-btn" class="primary">出发去冒险 <span>↗</span></button><button id="practice-btn" class="text-button">自由练习 <span>→</span></button></div>
    <div id="selection" hidden><div class="selection-heading"><button class="back-button" id="back-home">←</button><span>01 / 选择你的冒险</span></div><div class="mode-tabs"><button data-mode="quick" class="active">快速比赛<small>4 辆车 · 3 圈</small></button><button data-mode="time">计时赛<small>独行 · 本地幽灵</small></button><button data-mode="practice">自由练习<small>不限时 · 试车</small></button></div><div class="selection-heading vehicle-heading"><span>02 / 你的口袋搭档</span><span id="kart-type"></span></div><div class="kart-options">${KARTS.map((k,i)=>`<button data-kart="${i}" style="--kart-color:#${k.color.toString(16)}" class="${i===0?'active':''}" title="${k.name} · ${k.type}"><span class="mini-kart"><i></i></span><strong>${k.name}</strong></button>`).join('')}</div><div class="kart-detail"><div><strong id="kart-title"></strong><small id="kart-lore"></small></div><div id="kart-stats"></div></div><button class="primary" id="start-btn">开始比赛 <span>→</span></button><div id="local-record" class="record-note"></div></div>
    <div class="coming-links"><button data-info="cups">主题杯赛 <span>规划中</span></button><button data-info="ranked">在线排位 <span>需服务器</span></button></div></div>
    <aside class="hero-sticker"><span>MEET YOUR TINY RACER</span><strong id="hero-name">薄荷邮驹</strong><small>01 — 苔帽邮差 · 皮普</small><div class="sticker-line"></div><span class="sticker-chip">RC EDITION <b>1 : 12</b></span></aside>
    <footer class="track-card"><div class="track-index">01<small>FIRST STOP</small></div><div class="track-meta"><span>THE CLOCKWORK VALLEY</span><h2>${TRACK_NAME}</h2><p>苔绿山丘 / 巨型蘑菇 / 会呼吸的齿轮</p></div><div class="track-facts"><div><b>03</b><small>圈数</small></div><div><b>04</b><small>车手</small></div><div><b>★ ★ ☆</b><small>难度</small></div></div><span class="track-badge">全 3D 原创世界 <i>↗</i></span></footer>
    <div class="menu-bottom"><span>MADE FOR THE JOY OF THE RIDE.</span><span>W A S D 驾驶 <b>·</b> SHIFT 漂移 <b>·</b> 支持触屏 / 手柄</span></div></main>
    <section id="race-hud" hidden><div class="race-top"><div class="position-card"><span>POSITION</span><strong id="rank">1<small>/ 4</small></strong></div><div class="lap-card"><span>LAP</span><strong id="lap">1 <small>/ 3</small></strong><div id="checkpoint">CP 00 / 16</div></div><div class="timer-card"><span>RACE TIME</span><strong id="timer">00:00.000</strong><small id="best-time">BEST --:--.---</small></div><button class="icon-button" data-control="pause" aria-label="暂停">Ⅱ</button></div>
    <div class="race-bottom"><div class="map-panel"><canvas id="minimap" width="240" height="180"></canvas><small>发条蘑菇山谷 <span>↑</span></small></div><div class="drift-panel"><div id="grip-label">GRIP · 抓地行驶</div><div class="drift-meter"><i id="drift-fill"></i></div><small id="drift-hint">按住 SHIFT 转向蓄力，松开推进</small></div><div class="speed-panel"><strong id="speed">0</strong><span>KM/H</span><div id="speed-bar"></div></div></div>
    <div class="items-panel"><button class="item-slot" data-control="item1" id="slot-0"><span>+</span><small>E / 1</small></button><button class="item-slot secondary" data-control="item2" id="slot-1"><span>+</span><small>Q / 2</small></button><p id="item-name">驶过晶体箱，收集道具</p></div><div class="race-tip" id="race-tip">SHIFT 漂移　SPACE 跳跃　E 道具　R 复位　C 镜头</div><div class="countdown" id="countdown"></div></section>
    <div id="toast" role="status"></div><div id="touch-controls" hidden><div class="touch-utility"><button data-control="reset" aria-label="复位">↺ 复位</button><button data-control="camera" aria-label="切换镜头">◉ 镜头</button></div><div class="joystick" data-control="steer" aria-label="转向"><div class="stick"></div><span>STEER</span></div><div class="touch-actions"><button data-control="brake" class="touch-brake">刹车</button><button data-control="drift" class="touch-drift">漂移</button><button data-control="throttle" class="touch-gas">ϟ<small>加速</small></button><button data-control="jump" class="touch-jump">↑<small>跳跃</small></button></div></div>
    <div class="modal-backdrop" id="pause-modal" hidden><section class="dialog"><div class="eyebrow">TAKE A LITTLE BREATHER</div><h2>风景值得稍作停留。</h2><p>比赛已暂停。准备好就继续上路。</p><button id="resume-btn" class="primary">继续比赛 <span>→</span></button><button id="restart-btn" class="secondary-button">重新开始</button><button id="menu-btn" class="text-button">返回主菜单</button><div class="pause-keys">WASD 驾驶 · SHIFT 漂移 · SPACE 跳跃<br/>E / Q 道具 · S + E 后投 · DELETE 丢弃<br/>R 复位 · C 镜头 · ESC 暂停<br/>手柄：左杆驾驶 · RT/LT 油门/刹车 · 左杆按下漂移</div></section></div>
    <div class="modal-backdrop" id="result-modal" hidden><section class="dialog results"><div class="eyebrow">A LITTLE RACE. A BIG MEMORY.</div><div id="result-medal">01</div><h2 id="result-title">漂亮的一场冒险！</h2><p id="result-subtitle"></p><div class="result-time" id="result-time"></div><div id="result-laps"></div><div id="result-ranks"></div><p id="save-status"></p><button id="again-btn" class="primary">再跑一场 <span>↗</span></button><button id="result-menu-btn" class="text-button">返回王国</button></section></div>
    <div class="modal-backdrop" id="settings-modal" hidden><section class="dialog settings"><button class="close-dialog" id="close-settings" aria-label="关闭">×</button><div class="eyebrow">MAKE IT YOUR RIDE</div><h2>车库设置</h2><label>画质预设 <select id="quality"><option value="low">低 · 无阴影 / 1× 像素比</option><option value="medium">中 · 1024 阴影 / 1.5×</option><option value="high">高 · 2048 阴影 / 2×</option></select></label><label>触屏控件 <input type="checkbox" id="touch-toggle"/></label><label>音量 <input type="range" min="0" max="1" step=".05" id="volume"/></label><p>手柄：A 跳跃 · X / RB 道具 · LB 第二格<br/>B 复位 · Y 镜头 · 左杆按下漂移 · Start 暂停</p><p>建议横屏游玩。低画质优先保持驾驶响应。<br/>所有模型与声音均程序生成，无外部素材。</p><div id="device-info"></div></section></div>
    <div class="modal-backdrop" id="info-modal" hidden><section class="dialog info"><button class="close-dialog" id="close-info" aria-label="关闭">×</button><div id="info-content"></div></section></div>`;
    this.map=root.querySelector('#minimap')!;this.mapCtx=this.map.getContext('2d')!;
    this.touch=records.data.settings.touch??matchMedia('(pointer: coarse)').matches;root.classList.toggle('is-touch',this.touch);
    (root.querySelector('#quality') as HTMLSelectElement).value=records.data.settings.quality;(root.querySelector('#touch-toggle') as HTMLInputElement).checked=this.touch;(root.querySelector('#volume') as HTMLInputElement).value=String(records.data.settings.volume);this.updateSelection();
  }
  bind(actions:UIActions,preview:(i:number)=>void){this.actions=actions;const on=(id:string,fn:()=>void)=>this.root.querySelector(id)!.addEventListener('click',fn);
    on('#play-btn',()=>this.showSelection());on('#practice-btn',()=>{this.mode='practice';this.showSelection();});on('#back-home',()=>{this.selection='home';this.root.querySelector<HTMLElement>('#home-actions')!.hidden=false;this.root.querySelector<HTMLElement>('#selection')!.hidden=true;this.root.classList.remove('selecting');});
    this.root.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.onclick=()=>{this.mode=b.dataset.mode as Mode;this.updateSelection();});this.root.querySelectorAll<HTMLButtonElement>('[data-kart]').forEach(b=>b.onclick=()=>{this.kart=Number(b.dataset.kart);this.updateSelection();preview(this.kart);});
    on('#start-btn',()=>actions.start(this.mode,this.kart));on('#resume-btn',()=>actions.resume());on('#restart-btn',()=>actions.restart());on('#again-btn',()=>actions.restart());on('#menu-btn',()=>actions.menu());on('#result-menu-btn',()=>actions.menu());
    on('#settings-btn',()=>{if(this.lastState==='racing'||this.lastState==='countdown')actions.resume();this.root.querySelector<HTMLElement>('#settings-modal')!.hidden=false;});on('#close-settings',()=>{this.root.querySelector<HTMLElement>('#settings-modal')!.hidden=true;});
    this.root.querySelector<HTMLSelectElement>('#quality')!.onchange=e=>actions.quality((e.target as HTMLSelectElement).value as Quality);
    this.root.querySelector<HTMLInputElement>('#touch-toggle')!.onchange=e=>{this.touch=(e.target as HTMLInputElement).checked;this.root.classList.toggle('is-touch',this.touch);actions.touch(this.touch);};
    this.root.querySelector<HTMLInputElement>('#volume')!.oninput=e=>actions.volume(Number((e.target as HTMLInputElement).value));
    this.root.querySelectorAll<HTMLButtonElement>('[data-info]').forEach(b=>b.onclick=()=>{const content=b.dataset.info==='cups'?`<div class="eyebrow">THE NEXT CHAPTERS</div><h2>四个王国，十六段旅程。</h2><p>杯赛尚未开放。当前仅「发条蘑菇山谷」可驾驶。</p>${CUPS.map(c=>`<h3>${c.name}</h3><p>${c.tracks.join(' · ')}</p>`).join('')}`:`<div class="eyebrow">FAIR RACING, BY DESIGN</div><h2>真正的排位，需要真正的服务器。</h2><p>在线排位未开放，本原型不会伪造匹配结果。</p><h3>青铜 → 白银 → 黄金 → 铂金 → 钻石 → 大师</h3><p>规划采用 WebSocket 房间、服务器权威比赛状态、客户端预测与校正。MMR 与展示段位分离。详见项目的 multiplayer.md。</p>`;this.root.querySelector('#info-content')!.innerHTML=content;this.root.querySelector<HTMLElement>('#info-modal')!.hidden=false;});on('#close-info',()=>this.root.querySelector<HTMLElement>('#info-modal')!.hidden=true);
    this.root.querySelector('#brand-link')!.addEventListener('click',e=>e.preventDefault());
  }
  private showSelection(){this.selection='select';this.root.querySelector<HTMLElement>('#home-actions')!.hidden=true;this.root.querySelector<HTMLElement>('#selection')!.hidden=false;this.root.classList.add('selecting');this.updateSelection();}
  private updateSelection(){const k=KARTS[this.kart];this.root.querySelectorAll<HTMLButtonElement>('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===this.mode));this.root.querySelectorAll<HTMLButtonElement>('[data-kart]').forEach(b=>b.classList.toggle('active',Number(b.dataset.kart)===this.kart));this.set('#kart-type',k.type);this.set('#kart-title',`${k.vehicle} · ${k.title}`);this.set('#kart-lore',k.lore);this.set('#hero-name',k.vehicle);this.root.querySelector('#kart-stats')!.innerHTML=['极速','加速','操控'].map((n,i)=>`<div><span>${n}</span><b>${'▰'.repeat(k.stats[i])}<i>${'▰'.repeat(5-k.stats[i])}</i></b></div>`).join('');const rec=this.records.get(this.mode,k.id);this.set('#local-record',`本车最佳 ${formatTime(rec?.total??Infinity)} · ${this.mode==='time'&&rec?.ghost.length?'幽灵已就绪':'仅保存于此浏览器'}`);}
  loading(percent:number,text:string){this.set('#load-text',text);(this.root.querySelector('#load-bar') as HTMLElement).style.width=`${percent}%`;}
  ready(){this.root.querySelector<HTMLElement>('#loading')!.hidden=true;}
  error(message:string){this.set('#load-text',message);this.root.querySelector<HTMLElement>('#loading')!.hidden=false;}
  set(selector:string,text:string){const e=this.root.querySelector(selector)!;if(e.textContent!==text)e.textContent=text;}
  toast(message:string){this.set('#toast',message);this.toastTimer=2.5;this.root.querySelector('#toast')!.classList.add('visible');}
  private visible(id:string,v:boolean){this.root.querySelector<HTMLElement>(id)!.hidden=!v;}
  sync(state:string){if(state===this.lastState)return;this.lastState=state;const menu=state==='menu';this.visible('#menu',menu);this.visible('#brand',menu);this.visible('#race-hud',!menu);this.visible('#pause-modal',state==='paused');this.visible('#result-modal',state==='finished');this.visible('#touch-controls',!menu&&this.touch&&state!=='finished'&&state!=='paused');this.root.classList.toggle('in-race',!menu);if(menu){this.updateSelection();this.root.classList.toggle('selecting',this.selection==='select');}else this.root.classList.remove('selecting');}
  update(race:RaceManager,k:KartPhysics,dt:number,track:Track,gamepad:string,fps:number){this.sync(race.state);if(this.toastTimer>0){this.toastTimer-=dt;if(this.toastTimer<=0)this.root.querySelector('#toast')!.classList.remove('visible');}this.visible('#touch-controls',this.touch&&(race.state==='racing'||race.state==='countdown'));
    if(race.state==='menu')return;
    this.root.querySelector('#rank')!.innerHTML=`${k.rank}<small>/ ${race.karts.length}</small>`;this.root.querySelector('#lap')!.innerHTML=`${Math.min(k.lap+1,3)} <small>/ 3</small>`;this.set('#checkpoint',`CP ${k.lastCheckpoint.toString().padStart(2,'0')} / 16`);this.set('#timer',formatTime(k.finished?k.finishTime:race.elapsed));const best=this.records.get(race.mode,k.spec.id);this.set('#best-time',`BEST LAP ${formatTime(best?.lap??Infinity)}`);this.set('#speed',String(Math.round(Math.abs(k.speed)*3.6)));this.root.querySelector<HTMLElement>('#speed-bar')!.style.width=`${Math.min(100,Math.abs(k.speed)/42*100)}%`;
    this.set('#grip-label',k.stun>0?'SPIN · 打滑中':!k.grounded?k.trick?'TRICK · 特技落地推进':'AIR · 腾空':k.boost>0?'TURBO · 推进中':k.drift?`DRIFT · 蓄力 ${k.driftLevel} 级`:'GRIP · 抓地行驶');this.root.querySelector<HTMLElement>('#drift-fill')!.style.width=`${k.driftCharge/3.2*100}%`;this.root.querySelector<HTMLElement>('#drift-fill')!.style.background=k.driftLevel===3?'#ff9ccd':k.driftLevel===2?'#ffc979':'#a9f3e1';
    this.root.querySelector('#speed-fx')!.classList.toggle('active',k.boost>0&&race.state==='racing');
    const names:string[]=[];for(let i=0;i<2;i++){const item=k.rolling[i]>0?Object.keys(ITEMS)[Math.floor(race.elapsed*13)%4] as keyof typeof ITEMS:k.slots[i],element=this.root.querySelector(`#slot-${i}`)!;element.querySelector('span')!.textContent=item?ITEMS[item].icon:'+';element.classList.toggle('filled',!!item);element.classList.toggle('rolling',k.rolling[i]>0);if(item)names.push(k.rolling[i]>0?'装载中…':ITEMS[item].name);}this.set('#item-name',names.join(' / ')||'驶过晶体箱，收集道具');
    const countdown=race.state==='countdown'?String(Math.max(1,Math.ceil(race.countdown-.6))):race.goFlash>0?'GO!':'';this.set('#countdown',countdown);
    this.set('#race-tip',race.mode==='practice'?`自由练习 · ${Math.round(fps)} FPS · ${gamepad?'手柄已连接':'R 复位 / Esc 菜单'}`:gamepad?'手柄已连接 · 左杆按下漂移 · A 跳跃 · X 道具':'SHIFT 漂移　SPACE 跳跃　E / Q 道具　R 复位　C 镜头');
    if(k.lap!==this.lastLap){this.lastLap=k.lap;if(k.lap>0&&!k.finished)this.toast(`第 ${k.lap} 圈 ${formatTime(k.lapTimes.at(-1)??0)}${k.lap===2?' · 最后一圈！':''}`);}this.drawMap(track,race.karts);
    if(race.state==='finished')this.updateStandings(race);
  }
  reset(){this.lastState='';this.lastLap=0;this.visible('#settings-modal',false);this.visible('#info-modal',false);}
  private drawMap(track:Track,karts:KartPhysics[]){const ctx=this.mapCtx,s=.88,ox=121,oz=103;if(!this.mapBackground){const bg=document.createElement('canvas');bg.width=240;bg.height=180;const c=bg.getContext('2d')!;c.lineCap='round';c.lineJoin='round';c.beginPath();track.samples.forEach((p,i)=>i?c.lineTo(p.p.x*s+ox,p.p.z*s+oz):c.moveTo(p.p.x*s+ox,p.p.z*s+oz));c.closePath();c.strokeStyle='rgba(255,246,216,.25)';c.lineWidth=12;c.stroke();c.strokeStyle='#d8e7ce';c.lineWidth=5;c.stroke();const p=track.at(0).p;c.fillStyle='#ffce80';c.fillRect(p.x*s+ox-4,p.z*s+oz-5,8,10);this.mapBackground=bg;}
    ctx.clearRect(0,0,240,180);ctx.drawImage(this.mapBackground,0,0);for(const k of [...karts].reverse()){ctx.beginPath();ctx.arc(k.position.x*s+ox,k.position.z*s+oz,k.id===0?5:3.6,0,Math.PI*2);ctx.fillStyle=`#${k.spec.color.toString(16)}`;ctx.fill();ctx.strokeStyle=k.id===0?'white':'#274c47';ctx.lineWidth=2;ctx.stroke();}}
  result(race:RaceManager,k:KartPhysics,isBest:boolean,stored:boolean){this.set('#result-medal',String(k.rank).padStart(2,'0'));this.set('#result-title',isBest?'新的口袋纪录！':'漂亮的一场冒险！');this.set('#result-subtitle',`${TRACK_NAME} · ${race.mode==='time'?'计时赛':'快速比赛'} · ${k.spec.vehicle}`);this.set('#result-time',formatTime(k.finishTime));this.root.querySelector('#result-laps')!.innerHTML=k.lapTimes.map((t,i)=>`<div><span>LAP 0${i+1}</span><b>${formatTime(t)}</b></div>`).join('');this.set('#save-status',stored?'✓ 成绩已保存在此浏览器':'存储不可用；本次成绩仅保留在内存');this.updateStandings(race);}
  private updateStandings(race:RaceManager){this.root.querySelector('#result-ranks')!.innerHTML=[...race.karts].sort((a,b)=>a.rank-b.rank).map(k=>`<div><span>${k.rank}　${k.spec.name}${k.id===0?' · YOU':''}</span><b>${k.finished?formatTime(k.finishTime):`第 ${k.lap+1} 圈 · 比赛中`}</b></div>`).join('');}
}
