export class AudioManager {
  private ctx?:AudioContext;private gain?:GainNode;private engine?:OscillatorNode;private engineGain?:GainNode;volume=.35;private noise?:AudioBuffer;
  async unlock(){try{if(!this.ctx){this.ctx=new AudioContext();this.gain=this.ctx.createGain();this.gain.gain.value=this.volume;this.gain.connect(this.ctx.destination);this.engine=this.ctx.createOscillator();this.engine.type='sawtooth';this.engineGain=this.ctx.createGain();const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=450;this.engine.connect(filter);filter.connect(this.engineGain);this.engineGain.connect(this.gain);this.engineGain.gain.value=0;this.engine.start();this.noise=this.ctx.createBuffer(1,this.ctx.sampleRate*.2,this.ctx.sampleRate);const data=this.noise.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*(1-i/data.length);}
      await this.ctx.resume();}catch{/* Silent mode is fully playable. */}}
  setVolume(v:number){this.volume=v;if(this.gain&&this.ctx)this.gain.gain.setTargetAtTime(v,this.ctx.currentTime,.1);}
  update(speed:number,throttle:number,drift:boolean,active:boolean){if(!this.ctx||!this.engine||!this.engineGain)return;this.engine.frequency.setTargetAtTime(45+Math.abs(speed)*5+(throttle?14:0),this.ctx.currentTime,.08);this.engineGain.gain.setTargetAtTime(active?.028+throttle*.018+(drift?.01:0):0,this.ctx.currentTime,.1);}
  tone(name:string){if(!this.ctx||!this.gain)return;const ctx=this.ctx,now=ctx.currentTime,g=ctx.createGain();g.connect(this.gain);const osc=ctx.createOscillator();osc.connect(g);osc.type=name==='hit'?'triangle':'sine';const f=name==='go'?880:name==='tick'?440:name==='pickup'?1100:name==='boost'?220:name==='finish'?660:180;osc.frequency.setValueAtTime(f,now);osc.frequency.exponentialRampToValueAtTime(name==='boost'?900:f*.7,now+.2);g.gain.setValueAtTime(.13,now);g.gain.exponentialRampToValueAtTime(.001,now+.25);osc.start(now);osc.stop(now+.28);osc.onended=()=>{osc.disconnect();g.disconnect();};
    if(name==='hit'&&this.noise){const source=ctx.createBufferSource(),ng=ctx.createGain();source.buffer=this.noise;ng.gain.value=.15;source.connect(ng);ng.connect(this.gain);source.start();source.onended=()=>{source.disconnect();ng.disconnect();};}}
  suspend(){void this.ctx?.suspend();}
}
