import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
const base=process.env.PTK_URL||'http://localhost:5173';
const channel=process.env.PTK_BROWSER_CHANNEL||(existsSync('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe')?'msedge':undefined);
const browser=await chromium.launch({channel,headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
await mkdir('test-results',{recursive:true});
const errors=[],warnings=[],report={browser:browser.version(),checks:[],screenshots:[]};
const check=(name,value)=>{assert.ok(value,name);report.checks.push(name);console.log('PASS',name);};
function observe(page){page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning')warnings.push(m.text());});}
async function ready(page){await page.goto(`${base}/?test=1`);await page.waitForFunction(()=>window.__PTK__,null,{timeout:60000});await page.waitForTimeout(600);}
async function capture(page,name){await page.screenshot({path:`test-results/${name}.png`});report.screenshots.push(`${name}.png`);}
try{
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();observe(page);await ready(page);await page.waitForTimeout(1700);await capture(page,'desktop-menu');
  check('main menu visible',await page.locator('#play-btn').isVisible());await page.locator('#play-btn').click();await page.locator('[data-kart="2"]').click();await capture(page,'vehicle-selection');await page.locator('[data-kart="0"]').click();await page.locator('#start-btn').click();
  await page.waitForFunction(()=>window.__PTK__.snapshot().state==='racing');await page.keyboard.down('w');await page.waitForFunction(()=>window.__PTK__.snapshot().karts[0].speed>12,null,{timeout:15000});await page.keyboard.up('w');let s=await page.evaluate(()=>window.__PTK__.snapshot());check('real keyboard W drives dynamic chassis',s.karts[0].speed>12);
  await page.keyboard.press('Escape');await page.waitForTimeout(150);check('Escape pauses',await page.locator('#pause-modal').isVisible());const paused=await page.evaluate(()=>window.__PTK__.snapshot().elapsed);await page.waitForTimeout(250);check('paused time stays fixed',(await page.evaluate(()=>window.__PTK__.snapshot().elapsed))===paused);await page.keyboard.press('Escape');
  for(const [code,sign] of [['KeyA',-1],['KeyD',1],['ArrowLeft',-1],['ArrowRight',1]]){
    const result=await page.evaluate(({code,sign})=>{const d=window.__PTK__;d.start('practice',0);d.manual(true);d.teleport(.04);window.dispatchEvent(new KeyboardEvent('keydown',{code:'KeyW'}));d.advanceInput(65);const a=d.snapshot().karts[0],before=d.beginScreenProbe();window.dispatchEvent(new KeyboardEvent('keydown',{code}));d.advanceInput(30);const b=d.snapshot().karts[0];window.dispatchEvent(new KeyboardEvent('keyup',{code}));window.dispatchEvent(new KeyboardEvent('keyup',{code:'KeyW'}));return {yaw:(b.yaw-a.yaw)*sign,screen:(d.screenX()-before)*sign};},{code,sign});
    check(`${code} moves ${sign>0?'SCREEN-RIGHT':'SCREEN-LEFT'} in a fixed Three.js chase projection`,result.yaw<-.15&&result.screen>.015);
  }
  await page.evaluate(()=>{const d=window.__PTK__;d.manual(true);d.start('quick',0);d.manual(true);d.advance(220);});
  // Complete a race through the real keyboard InputManager. AI supplies steering suggestions only;
  // the harness quantizes them into W/A/S/D/Shift/E/Q key events, never writes kart poses or lap state.
  let keyboardFinished=false;for(let chunk=0;chunk<50;chunk++){
    s=await page.evaluate(()=>{const d=window.__PTK__;window.__keys??={};window.__duty??=0;for(let n=0;n<300;n++){
      const s=d.snapshot();if(s.karts[0].finished)return s;const c=d.suggest();window.__duty+=Math.abs(c.steer);const turn=window.__duty>=1;if(turn)window.__duty-=1;
      const desired={KeyW:c.throttle>.3,KeyS:c.brake>.2,KeyA:turn&&c.steer<0,KeyD:turn&&c.steer>0,ShiftLeft:c.drift,KeyE:c.item1,KeyQ:c.item2};
      for(const [code,on] of Object.entries(desired)){if(!!window.__keys[code]!==on){window.dispatchEvent(new KeyboardEvent(on?'keydown':'keyup',{code,bubbles:true,cancelable:true}));window.__keys[code]=on;}}
      d.advanceInput(1);
    }return d.snapshot();});
    if(chunk%5===0)console.log('keyboard progress',s.elapsed.toFixed(1),s.karts.map(k=>`${k.lap}:${k.cp}`));if(s.karts[0].finished){keyboardFinished=true;break;}
  }
  check('keyboard input chain completes 3 laps',keyboardFinished);await page.evaluate(()=>{for(const code of Object.keys(window.__keys)){window.dispatchEvent(new KeyboardEvent('keyup',{code}));}window.__keys={};});
  for(let i=0;i<12&&!s.karts.every(k=>k.finished);i++)s=await page.evaluate(()=>window.__PTK__.advance(600));check('all three colliding AI finish in browser',s.karts.every(k=>k.finished));check('three player lap times persisted',Object.values(await page.evaluate(()=>window.__PTK__.records().records)).some(r=>r.total>0));await page.waitForTimeout(300);await capture(page,'race-results');report.quickRace=s;
  // Isolated time trial + recorded ghost playback.
  await page.evaluate(()=>{const d=window.__PTK__;d.start('time',1);d.manual(true);d.autopilot(true);});for(let i=0;i<30;i++){s=await page.evaluate(()=>window.__PTK__.advance(600));if(s.karts[0].finished)break;}
  check('single-player three-lap time trial finishes',s.karts.length===1&&s.karts[0].finished);const rec=await page.evaluate(()=>Object.values(window.__PTK__.records().records).find(r=>r.ghost.length>0));check('10 Hz ghost recording saved',rec?.ghost.length>500);report.timeTrial={total:rec.total,lap:rec.lap,samples:rec.ghost.length};
  await page.reload();await page.waitForFunction(()=>window.__PTK__);await page.evaluate(()=>{window.__PTK__.start('time',1);window.__PTK__.manual(true);window.__PTK__.advance(250);});s=await page.evaluate(()=>window.__PTK__.snapshot());check('best record survives reload; ghost loads',s.ghostFrames===rec.ghost.length);await page.waitForTimeout(200);await capture(page,'time-trial-ghost');
  // Gamepad API edge/deadzone checks with an injected virtual standard-layout pad, not a physical-device claim.
  await page.evaluate(()=>{window.__pad={id:'PTK Virtual Standard Gamepad',connected:true,index:0,mapping:'standard',axes:[.1,0,0,0],buttons:Array.from({length:17},()=>({pressed:false,touched:false,value:0})),timestamp:0};Object.defineProperty(navigator,'getGamepads',{value:()=>[window.__pad],configurable:true});window.__PTK__.start('practice',0);window.__PTK__.manual(true);window.__PTK__.give('battery');window.__PTK__.give('battery',1);window.__pad.buttons[7]={pressed:true,touched:true,value:1};});
  s=await page.evaluate(()=>window.__PTK__.advanceInput(90));check('virtual RT drives; analog deadzone accepted',s.karts[0].speed>15&&Math.abs(s.karts[0].steering)<.001);await page.evaluate(()=>{window.__pad.buttons[2]={pressed:true,value:1};});s=await page.evaluate(()=>window.__PTK__.advanceInput(5));check('gamepad X uses first slot once',s.karts[0].boost>1&&s.karts[0].slots[0]===null&&s.karts[0].slots[1]==='battery');await page.evaluate(()=>window.__PTK__.give('battery'));s=await page.evaluate(()=>window.__PTK__.advanceInput(90));check('held gamepad X does not retrigger',s.karts[0].slots[0]==='battery');for(const sign of [-1,1]){const result=await page.evaluate(sign=>{const d=window.__PTK__;d.start('practice',0);d.manual(true);d.teleport(.04);window.__pad.axes[0]=0;window.__pad.buttons[2]={pressed:false,value:0};d.advanceInput(65);const a=d.snapshot().karts[0],before=d.beginScreenProbe();window.__pad.axes[0]=sign*.7;d.advanceInput(30);const b=d.snapshot().karts[0];return {yaw:(b.yaw-a.yaw)*sign,screen:(d.screenX()-before)*sign};},sign);check(`gamepad axis ${sign} moves ${sign>0?'SCREEN-RIGHT':'SCREEN-LEFT'}`,result.yaw<-.1&&result.screen>.015);}await page.evaluate(()=>{window.__pad.connected=false;});
  // Quality, resize and recovery.
  await page.evaluate(()=>{window.__PTK__.start('practice',0);window.__PTK__.manual(true);window.__PTK__.teleport(.44);window.__PTK__.reset();});s=await page.evaluate(()=>window.__PTK__.snapshot());check('manual reset returns to validated CP, not arbitrary position',s.karts[0].t<.01&&s.karts[0].cp===0);
  await page.setViewportSize({width:1024,height:640});await page.waitForTimeout(200);check('canvas responds to resizing',await page.locator('#viewport canvas').evaluate(e=>e.clientWidth===1024&&e.clientHeight===640));await capture(page,'desktop-race');report.render=await page.evaluate(()=>window.__PTK__.renderer());await context.close();
  // Real Chromium multi-touch events via CDP, in a mobile viewport. Full three-lap touch drive uses
  // the same planner as above, but all throttle, brake, steering and drift enter via touchscreen UI.
  const mobile=await browser.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true,deviceScaleFactor:1}),mp=await mobile.newPage();observe(mp);await ready(mp);await capture(mp,'mobile-menu');await mp.locator('#play-btn').tap();await mp.locator('[data-mode="time"]').tap();await mp.locator('#start-btn').tap();await mp.evaluate(()=>{window.__PTK__.manual(true);window.__PTK__.advance(220);});
  check('touch UI auto-detected',await mp.locator('#touch-controls').isVisible());const client=await mobile.newCDPSession(mp);
  const coords=await mp.evaluate(()=>Object.fromEntries(['steer','throttle','brake','drift','item1','item2'].map(name=>{const r=document.querySelector(`[data-control="${name}"]`).getBoundingClientRect();return [name,{x:r.x+r.width/2,y:r.y+r.height/2,width:r.width}];})));
  for(const sign of [-1,1]){
    await mp.evaluate(()=>{const d=window.__PTK__;d.start('practice',0);d.manual(true);d.teleport(.04);});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:2,x:coords.throttle.x,y:coords.throttle.y}]});const a=(await mp.evaluate(()=>window.__PTK__.advanceInput(65))).karts[0];const before=await mp.evaluate(()=>window.__PTK__.beginScreenProbe());await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:coords.steer.x+sign*.65*coords.steer.width*.35,y:coords.steer.y},{id:2,x:coords.throttle.x,y:coords.throttle.y}]});const b=(await mp.evaluate(()=>window.__PTK__.advanceInput(30))).karts[0];await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const screen=((await mp.evaluate(()=>window.__PTK__.screenX()))-before)*sign;check(`real touch joystick ${sign>0?'RIGHT':'LEFT'} moves matching SCREEN direction`,(b.yaw-a.yaw)*sign<-.15&&screen>.015);
  }
  await mp.evaluate(()=>{const d=window.__PTK__;d.start('practice',0);d.manual(true);d.teleport(.34);});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:2,x:coords.throttle.x,y:coords.throttle.y}]});await mp.evaluate(()=>window.__PTK__.advanceInput(65));await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{id:1,x:coords.steer.x-.24*coords.steer.width*.35,y:coords.steer.y},{id:2,x:coords.throttle.x,y:coords.throttle.y},{id:4,x:coords.drift.x,y:coords.drift.y}]});s=await mp.evaluate(()=>window.__PTK__.advanceInput(80));check('three simultaneous touch points accelerate, steer and charge drift',s.karts[0].charge>.55);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});s=await mp.evaluate(()=>window.__PTK__.advanceInput(1));check('releasing touch drift actually grants turbo',s.karts[0].boost>0);
  await mp.evaluate(()=>{const d=window.__PTK__;d.start('time',0);d.manual(true);d.advance(220);});
  let prevIds='',touchFinished=false,maxCharge=0;for(let i=0;i<2600;i++){
    const data=await mp.evaluate(()=>({c:window.__PTK__.suggest(),s:window.__PTK__.snapshot()}));s=data.s;if(s.karts[0].finished){touchFinished=true;break;}maxCharge=Math.max(maxCharge,s.karts[0].charge);const c=data.c;
    const points=[{id:1,x:coords.steer.x+c.steer*coords.steer.width*.35,y:coords.steer.y}];for(const [idx,name,on] of [[2,'throttle',c.throttle>.3],[3,'brake',c.brake>.2],[4,'drift',c.drift],[5,'item1',c.item1],[6,'item2',c.item2]])if(on)points.push({id:idx,x:coords[name].x,y:coords[name].y});
    const ids=points.map(p=>p.id).join(',');if(ids!==prevIds){if(prevIds)await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:points});}else await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:points});prevIds=ids;
    s=await mp.evaluate(()=>window.__PTK__.advanceInput(6));if(i%200===0)console.log('touch progress',s.elapsed.toFixed(1),s.karts[0].lap,s.karts[0].cp);if(i===40){await mp.waitForTimeout(150);await capture(mp,'mobile-multitouch-race');}
  }
  await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});check('real CDP multi-touch input completes three laps',touchFinished);report.touchRace={time:s.karts[0].time,maxDriftCharge:maxCharge};await mp.waitForTimeout(200);await capture(mp,'mobile-results');
  await mp.setViewportSize({width:390,height:844});await mp.locator('#result-menu-btn').tap();await mp.waitForTimeout(500);await capture(mp,'mobile-portrait');check('portrait menu has no horizontal overflow',await mp.evaluate(()=>document.documentElement.scrollWidth===window.innerWidth));await mp.locator('#settings-btn').tap();await mp.locator('#quality').selectOption('low');check('low quality pixel ratio capped',await mp.evaluate(()=>window.__PTK__.renderer().pixelRatio<=1));await mobile.close();
  check('no browser console errors or uncaught exceptions',errors.length===0);report.warnings=[...new Set(warnings)];report.errors=errors;report.status='passed';
}catch(e){report.status='failed';report.failure=String(e);report.errors=errors;console.error(e);process.exitCode=1;}
finally{await writeFile('test-results/browser-report.json',JSON.stringify(report,null,2));await browser.close();}
